# Site settings
title: GeorgeMac
email: me@georgemac.com
description: > # this means to ignore newlines until "baseurl:"
  Brightonian, Go Developer and Skater
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://georgemac.com" # the base hostname & protocol for your site
twitter_username: GeorgeMacr
github_username:  GeorgeMac

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
